# Generated by Django 4.1.1 on 2022-10-18 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_users", "0005_alter_user_username"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="birth_date",
            field=models.DateField(blank=True, default="2022-01-01"),
        ),
        migrations.AlterField(
            model_name="user",
            name="first_name",
            field=models.CharField(
                blank=True, default=None, max_length=30, verbose_name="Имя"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="last_name",
            field=models.CharField(
                blank=True, default=None, max_length=30, verbose_name="Фамилия"
            ),
        ),
    ]
