# Generated by Django 4.1.1 on 2022-10-18 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_users", "0006_alter_user_birth_date_alter_user_first_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="first_name",
            field=models.CharField(blank=True, max_length=30, verbose_name="Имя"),
        ),
        migrations.AlterField(
            model_name="user",
            name="last_name",
            field=models.CharField(blank=True, max_length=30, verbose_name="Фамилия"),
        ),
    ]
