# Generated by Django 4.1.1 on 2022-10-18 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_users", "0007_alter_user_first_name_alter_user_last_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="photo",
            field=models.ImageField(blank=True, null=True, upload_to="photo/%Y/%M/%D/"),
        ),
    ]
